LehtiTown_MapScripts::
	.byte 0


LehtiTownTechnologyGuy::
# 5 "data/maps/LehtiTown/scripts.pory"
	msgbox LehtiTownTechnologyGuy_Text_0, MSGBOX_NPC
	end


LehtiTownGirl::
	return


LehtiTownOldWoman::
	return


LehtiTownFisherman::
	return


LehtiTownWallyStarterScene::
	return


LehtiTownPlayerMailbox::
	return


LehtiTownRivalMailbox::
	return


LehtiTownLabSign::
	return


LehtiTownLabMailbox::
	return


LehtiTownRailwaySign::
	return


LehtiTownTechnologyGuy_Text_0:
# 5 "data/maps/LehtiTown/scripts.pory"
	.string "Technology is amazing! You can connect\n"
	.string "to the internet with Game Boy games!$"
