MauvilleRocketHideout2Sub_MapScripts::
# 2 "data/maps/MauvilleRocketHideout2Sub/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, MauvilleRocketHideout2Sub_MapScripts_MAP_SCRIPT_ON_TRANSITION
	.byte 0

MauvilleRocketHideout2Sub_MapScripts_MAP_SCRIPT_ON_TRANSITION:
# 3 "data/maps/MauvilleRocketHideout2Sub/scripts.pory"
	setflag FLAG_TEMP_2
# 4 "data/maps/MauvilleRocketHideout2Sub/scripts.pory"
	setflag FLAG_TEMP_3
# 5 "data/maps/MauvilleRocketHideout2Sub/scripts.pory"
	setflag FLAG_TEMP_4
	return


CageGuard_Grunt::
	return

